name: Update Baseball Statistics

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
      
      - name: Install base packages
        run: |
          Rscript -e "install.packages(c('dplyr', 'purrr', 'cli', 'remotes'), repos='https://cloud.r-project.org')"
      
      - name: Download and install baseball packages
        run: |
          # Create packages directory
          mkdir -p packages
          
          # Download package archives
          curl -L https://github.com/BillPetti/baseballr/archive/refs/heads/master.tar.gz -o packages/baseballr.tar.gz
          curl -L https://github.com/robert-frey/collegebaseball/archive/refs/heads/master.tar.gz -o packages/collegebaseball.tar.gz
          
          # Install from local files
          Rscript -e "remotes::install_local('packages/baseballr.tar.gz', dependencies = TRUE)"
          Rscript -e "remotes::install_local('packages/collegebaseball.tar.gz', dependencies = TRUE)"
      
      - name: Run data collection script
        run: Rscript get_stats.R
      
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          CURRENT_YEAR=$(date +%Y)
          git add "data/d3_batting_${CURRENT_YEAR}.csv" "data/d3_pitching_${CURRENT_YEAR}.csv"
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update baseball statistics data [automated]" && git push)
