name: Update Baseball Statistics

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
      
      - name: Install base packages
        run: |
          Rscript -e "install.packages(c('dplyr', 'purrr', 'cli', 'remotes'), repos='https://cloud.r-project.org')"
      
      - name: Install baseball packages from local files
        run: |
          # Verify packages directory exists
          ls -la packages/
          
          # Install from local files with all dependencies
          Rscript -e "remotes::install_local('packages/baseballr-master.tar.gz', dependencies = TRUE)"
          Rscript -e "remotes::install_local('packages/collegebaseball-master.tar.gz', dependencies = TRUE)"
      
      - name: Verify package installation
        run: |
          Rscript -e "installed.packages()[,'Package']"
      
      - name: Run data collection script
        run: Rscript ./scrapers/get_stats.R
      
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          CURRENT_YEAR=$(date +%Y)
          git add "data/d3_batting_${CURRENT_YEAR}.csv" "data/d3_pitching_${CURRENT_YEAR}.csv"
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update baseball statistics data [automated]" && git push)
